version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - cd todo
      - mvn clean install package -DskipTests
  post_build:
    commands:
      - echo "Entered the post-build phase"
      - mv target/todo-0.0.1-SNAPSHOT.jar ./
    artifacts:
      files:
        - todo/todo-0.0.1-SNAPSHOT.jar 
